name: gm_motors
description: Info about GM Motor Cars

version: 1.0.5

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  l: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  firebase_auth: any
  firebase_core: any
  shared_preferences: ^2.2.0
  cloud_firestore: any
  firebase_storage: any
  cached_network_image: ^3.2.3
  rate_my_app: any
  firebase_remote_config: ^4.2.4
  firebase_analytics: ^10.4.4
  model_viewer_plus: ^1.6.1
  curved_navigation_bar: ^1.0.3
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/astronaut.glb
    - assets/images/back/
